
alias code="codium"
alias cdcode="cdcodium"
alias mkcdcode="mkcdcodium"
alias grep="grep --color=auto"
alias ll="exa -l"
alias ls="ll"
alias v="nvim"
alias c="clear"
alias cdc="cdcode"
alias mkcdc="mkcdcode"
alias l="ls"
alias vz="nvim $ZDOTDIR/.zshrc && reload"
alias vn="nvim $HOME/.config/nvim/init.lua"
alias mk="mkdir"
alias cdtemp="cd $(mktemp -d)"
alias copy="xclip -selection clipboard"
alias ip="ip --color=always"
alias curl-novpn="curl --interface wlp1s0"
alias clip="xclip -selection clipboard"
alias npms="jq '.scripts' package.json"
